apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-13T07:04:01Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "3002"
  uid: c40840fb-0391-4d33-aeb5-9bdd8a245a3f
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.98.2.162
  clusterIPs:
  - 10.98.2.162
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32086
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
